export const formatDate = (date) => {
  const d = new Date(date)
  const day = String(d.getDate()).padStart(2, '0')
  const month = String(d.getMonth() + 1).padStart(2, '0')
  const year = d.getFullYear()
  return `${year}-${month}-${day}`
}

export const generateSlipNumber = (prefix) => {
  const date = new Date()
  const month = date.toLocaleString('default', { month: 'short' }).toUpperCase()
  const year = date.getFullYear()
  const random = Math.floor(Math.random() * 100)
  return `${prefix}-${month}-${year}-${random}`
}

export const generateGRN = () => {
  return generateSlipNumber('GRN')
}

export const generateST = () => {
  return generateSlipNumber('ST')
}

export const generateMR = () => {
  return generateSlipNumber('MR')
}

/**
 * Generate MR number preview based on date
 * Format: MR-MONTH(ABV)-YEAR-XXX (where XXX is a placeholder for the sequential number)
 * The actual sequential number will be generated by the backend
 * @param {Date|string} date - The date to use for month/year
 * @param {number} sequenceNumber - Optional sequence number (defaults to 1 for preview)
 */
export const generateMRPreview = (date = null, sequenceNumber = 1) => {
  const d = date ? new Date(date) : new Date()
  const month = d.toLocaleString('default', { month: 'short' }).toUpperCase()
  const year = d.getFullYear()
  const numberStr = String(sequenceNumber).padStart(3, '0')
  return `MR-${month}-${year}-${numberStr}`
}

export const formatCurrency = (amount) => {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 2,
  }).format(amount)
}



